# paths:
repo_path:           Multilingual_NER/
utils_path:          python/utils/

# path to models (relative to demo.py)
models_path:         '../models/'

### NOTE:            these are all specified relative to the location of main.py

# data paths:
## en data:
conll_path:          '../data/en/CONLL2003/'
ee_path:             '../data/en/emerging_entities_17/'
en_combined_path:    '../data/en/combined/'
## ru data:
factRu_path:         "../data/ru/factRuEval-2016/"
st_path:             "../data/ru/shared_task_2019/"
ru_combined_path:    '../data/ru/combined/'

# language-specific parameters for training stage
en:
  train_data_path:   "../data/en/combined/train_combined_std.txt"
  dev_data_path:     "../data/en/combined/dev_combined_std.txt"
  test_data_path:    "../data/en/combined/test_combined_std.txt"
  label_types:
    - "B-PER"
    - "I-PER"
    - "B-LOC"
    - "I-LOC"
    - "B-ORG"
    - "I-ORG"
    - "B-MISC"
    - "I-MISC"
    - "O"
  model:             'bert-base-cased'

ru:
  train_data_path:   "../data/ru/combined/devset_combined.txt"
  dev_data_path:     "../data/ru/combined/testset_combined.txt"
  label_types:
    - "PER"
    - "LOC"
    - "ORG"
    - "MISC"
    - "EVT"
    - "PRO"
    - "O"
  model:             'bert-base-multilingual-cased'

demo_text:
  en:                On this day in 1957, a California Superior Court judge ruled that "Howl", a poem by Allen Ginsberg, was of "redeeming social importance" and thus not obscene.
  ru:                МОСКВА, 4 авг - РИА Новости. Россия рассчитывает, что США воздействуют на Тбилиси в связи с обострением ситуации в зоне грузино-осетинского конфликта. Об этом статс-секретарь - заместитель министра иностранных дел России Григорий Карасин заявил в телефонном разговоре с заместителем госсекретаря США Дэниэлом Фридом.

parallel_demo_text:
  en:                Lately, with gold prices up more than 300% over the last decade, it is harder than ever. Just last December, fellow economists Martin Feldstein and Nouriel Roubini each penned op-eds bravely questioning bullish market sentiment, sensibly pointing out gold’s risks.
  ru:                Еще в декабре прошлого года экономисты-коллеги Мартин Фельдштейн и Нуриэль Рубини опубликовали свои пророческие статьи в колонках альтернативных мнений, храбро ставя в них под вопрос стремление игры на повышение, благоразумно указывая на риски золота.
